box      = 'hashicorp/precise64'
ram      = '2048'

Vagrant.configure(2) do |config|
  config.vm.provider "virtualbox" do |v|
  	v.name = "eps_playground"
	v.memory = ram
  end
  config.vm.box = box
  config.vm.box_check_update = false
  config.vm.provision "shell", path: "provisionBasic.sh"
  config.vm.provision "shell", path: "provisionEPS.sh"
end